### PR TITLE
🐛 💄 Fix skills cards styling

### LINKED ISSUE #254: Skills cards on add skill list selector have buttons of different sizes and lack spacing with the scrollbar
image

### PR DESCRIPTION
**Pull request by Ked57**
image

closes #254

### CODE REVIEW

File: src/components/AddSkilListSelector.tsx [hunk 1]
```diff
@@ -56,19 +56,23 @@ const AddSkillListSelector = ({
...
+              }
             >
-              <span className="text-l">{skill.name}</span>
-              <button
-                onClick={() => action(skill)}
-                className="rounded-full border px-2 text-light-red dark:text-dark-red"
-              >
-                {t("skills.add")}
-              </button>
+              <div className="flex flex-row justify-between w-full">
```
Comment (benjaminbrgs) [inline src/components/AddSkilListSelector.tsx:67]:
```suggestion
              <div className="flex flex-row justify-between w-full items-center">
```

I would suggest adding this class to keep the vertical align in the center

**Review by benjaminbrgs — CHANGES_REQUESTED** [review]

**Review by benjaminbrgs — APPROVED** [review]
👌🏼
