### PR TITLE
:lipstick: refacto and fix of Statistics section

### LINKED ISSUE #236: improve and fix statistics section
Actually it looks like this : 

Capture d’écran de 2022-09-26 11-27-19

On Figma it looks like this : 

Capture d’écran de 2022-09-26 11-28-13

### PR DESCRIPTION
**Pull request by MailyLehoux**
resolve #236

### CODE REVIEW

**Comment by MailyLehoux** [comment]
I've deleted the "profile" objective for some reasons : 

- Can't add a button such as the new UI (Add behaviors, add platforms ect). It's weird
- Not usefull. The old objectives was to **add 3 topics and an agency** to get the profile achievement. But now, add the agency is a mandatory to use Skillz, and adding 3 topics does not mean much. Maybe should we add certifications/bot notifications ect. ? 

I think we should review new rules for this achievement to keep it.

File: i18n/fr.js [hunk 1]
```diff
@@ -210,27 +210,17 @@ export default {
     monthStreak: "Mois d'affilés",
     sentenceRankIncodming1: "Il te reste ",
     sentenceRankIncodming2: "xp à avoir pour être promu",
+    add: "Add %label%",
```
Comment (benjaminbrgs) [inline i18n/fr.js:213]:
```suggestion
    add: "Ajouter des %label%",
```

File: src/components/profile/statistics/Statistics.tsx [hunk 2]
```diff
@@ -34,57 +25,32 @@ export const Statistics = ({
           : t("statistics.titleSection")}
       </h2>
       <BadgeSubojectivesCategoryCompletion
-        themeToCompare="practices"
+        label={skillsDatas?.find((skill) => skill.label === "practices").label}
```
Comment (benjaminbrgs) [inline src/components/profile/statistics/Statistics.tsx:28]:
```suggestion
        label={"practices"}
```
We're searching for a skill which has the label "practices" and take the value of its label.
Obviously it will be "practices". So can write it directly

File: src/components/profile/statistics/Statistics.tsx [hunk 3]
```diff
@@ -34,57 +25,32 @@ export const Statistics = ({
...
-        descriptionSubobjective={
-          myStatistics ? t("statistics.subobjectivesLegends.Practices") : ""
-        }
+        src="/img/badges/hexagone.svg"
         countSkills={filterCountSkills("practices")}
+        myStatistics={myStatistics}
       />
       <BadgeSubojectivesCategoryCompletion
-        themeToCompare="activities"
+        label={skillsDatas?.find((skill) => skill.label === "activities").label}
```
Comment (benjaminbrgs) [inline src/components/profile/statistics/Statistics.tsx:35]:
```suggestion
        label={"activities"}
```

File: src/components/profile/statistics/Statistics.tsx [hunk 4]
```diff
@@ -34,57 +25,32 @@ export const Statistics = ({
...
-        descriptionSubobjective={
-          myStatistics ? t("statistics.subobjectivesLegends.Activities") : ""
-        }
+        src="/img/badges/hexagone.svg"
         countSkills={filterCountSkills("activities")}
+        myStatistics={myStatistics}
       />
       <BadgeSubojectivesCategoryCompletion
-        themeToCompare="knowledge"
+        label={skillsDatas?.find((skill) => skill.label === "knowledge").label}
```
Comment (benjaminbrgs) [inline src/components/profile/statistics/Statistics.tsx:42]:
```suggestion
        label={"knowledge"}
```

File: src/components/profile/statistics/Statistics.tsx [hunk 5]
```diff
@@ -34,57 +25,32 @@ export const Statistics = ({
...
-        descriptionSubobjective={
-          myStatistics ? t("statistics.subobjectivesLegends.Knowledge") : ""
-        }
+        src="/img/badges/hexagone.svg"
         countSkills={filterCountSkills("knowledge")}
+        myStatistics={myStatistics}
       />
       <BadgeSubojectivesCategoryCompletion
-        themeToCompare="behaviors"
+        label={skillsDatas?.find((skill) => skill.label === "behaviors").label}
```
Comment (benjaminbrgs) [inline src/components/profile/statistics/Statistics.tsx:49]:
```suggestion
        label={"behaviors"}
```

**Review by benjaminbrgs — CHANGES_REQUESTED** [review]
Good 👌🏼
Maybe put the "add" button on the right, with the same border-radius of all other buttons in Skillz
And left-align elements, like this :
image

File: src/components/profile/statistics/Statistics.tsx (hunk 2 above)
Comment (MailyLehoux) [reply src/components/profile/statistics/Statistics.tsx:28]: omg I'm completely matrixed by .find 💩thanks to have noticed that !
